### ISSUE TITLE
Create a ListSelect Component

### ISSUE THREAD

**Issue by Pearlsky** [chingu-voyages/v43-tier3-team-36#125]
**__Task Description__**
The idea for this is to use @headlessui `Listbox(Select)` component to build a `ListSelect` UI component for this product. This component among other things will be useful to help users select a comic book from the list of comic books in their collection, to make an exchange.

**Comment by TazDeCoder** [comment]
@Pearlsky we definitely need this for other aspects of the app - go ahead!
