### ISSUE TITLE
Edit Your Comic Book Collection

### ISSUE THREAD

**Issue by TazDeCoder** [chingu-voyages/v43-tier3-team-36#23]
As a user I must be able to edit my own comic book collection so I can reflect my real-life collection

**__User Story Description__**
Users can update their own comic book collection to ensure it is up-to-date with their physical collection

**__Steps to Follow (optional)__**
- [x] Retrieve/Fetch comics from **current user** to be edited
- [x] Create an action to **trigger "edit mode"**
- [x] Allow user to remove comics from only **their collection**
- [x] Update **mutated comics** on the **backend**
- [x] Responsive UI

**__Additional Considerations__**
Refer to Figma design wire-frames - 'Profile' view/screen

**Comment by TazDeCoder** [comment]
@beblicarl can you please setup the route on the backend to be able mutate the comic collection of the current user such that they are able to delete comics

**Comment by beblicarl** [comment]
> @beblicarl can you please setup the route on the backend to be able mutate the comic collection of the current user such that they are able to delete comics

sure, I will work on this
