### ISSUE TITLE
Exchange Comic Books With Others

### ISSUE THREAD

**Issue by TazDeCoder** [chingu-voyages/v43-tier3-team-36#26]
**As a user I must be able to exchange comic books with others so I can make trade with other collectors**

**__User Story Description__**
Users can exchange comic books present in their collection as long as both parties agree and are happy with the trade then it can be initiated

**__Steps to Follow (optional)__**
- [x] Set up API endpoint to request an **exchange** for a comic book from **another collector**
- [x] Add API service for **exchanging comics** from backend
- [x] Add dialog to **request an exchange for a comic book** from **trade offer**
- [x] Add Responsive UI

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by Pearlsky** [comment]
@Danthesage01 @beblicarl please let's create separate fe & be branches for this. hope that'd okay
