### ISSUE TITLE
Search for Marvel Comic Books

### ISSUE THREAD

**Issue by TazDeCoder** [chingu-voyages/v43-tier3-team-36#29]
**As a user I should be able to search for any comic book from Marvel so I can learn more about it**

**__User Story Description__**
The Marvel API would be used as a source for all comics that would be made available for the user to make searches and queries on

**__Steps to Follow (optional)__**
- [ ] Step 1

**__Additional Considerations__**
Any supplemental information including unresolved questions, links to external resources, screenshots, etc.

**Comment by Pearlsky** [comment]
@TazDeCoder, hi, I want to clarify, should the ResponseData containing comics that match the search queries be used to populate the explore/comics tab at that moment? or should the ResponseData be displayed in a dropdown?

**Comment by TazDeCoder** [comment]
The response data should populate the explore/comic view based on the queries; for instance, I search "X-Men" and query by "Wolverine" then should display comics X-Men comics with Wolverine in it

**Comment by Pearlsky** [comment]
@TazDeCoder I just noticed that @fmtabbara has already implemented this.
