### ISSUE TITLE
Create Offers List & Offer Item Components

### ISSUE THREAD

**Issue by Pearlsky** [chingu-voyages/v43-tier3-team-36#80]
**Task Description**
Users should be able to view trade offers of various users on the `explore/offers` page. Users should also be able to view the trade offers of a select collector on that collector's profile page.

- [x] Create the `OffersItem` component
- [x] Create the `OffersList` component

**Comment by TazDeCoder** [comment]
Can you please write **at least write a brief description** of what you are going to do and how
