### ISSUE TITLE
Alert component not visable when page scrolled

### ISSUE THREAD

**Issue by fmtabbara** [chingu-voyages/v43-tier3-team-36#93]
**Describe the problem**

The Alert Component doesn't stick to the top of the page. If you're scrolled down the page a little and the Alert Component
is displayed, you dont see it.

**Actual behavior**

Alert component not sticky

**Expected behavior**

Alert component should be sticky

**To Reproduce**

Search comics
Scroll down the page
Add a comic

**Comment by TazDeCoder** [comment]
@Pearlsky be sure to also specify the **z-index quite high** because I came across this similar issue with my **Modal** component as it doesn't the display alert over it

**Comment by Pearlsky** [comment]
@TazDeCoder , thank you for this. alright
